spring:
  application:
    name: rocketmq_consumer
  cloud:
    stream:
      bindings:
        consumerChannelEmail:
          destination: TopicEmail
          group: GroupEmail
      rocketmq:
        binder:
          name-server: 127.0.0.1:9877
        bindings:
          consumerChannelEmail:
            tags: tag1
            keys: key1||key2

server:
  port: 8072


